version: '3.1'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - 8000:8000
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
