services:
  mongo:
    image: mongo
    container_name: url-shortener-mongo
    restart: unless-stopped
    ports:
      - ${MONGO_PORT}:27017 # Direct mapping for MongoDB port
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - ./data:/data/db

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: url-shortener-api
    depends_on:
      - mongo
    ports:
      - "8000:8000"
    expose:
      - ${PORT}
    env_file:
      - .env
    volumes:
      - ./src:/usr/src/src
      - /usr/src/node_modules
